name: aguazullavapp
description: Proyecto para lavadero de carros, control de pagos, etc.
publish_to: "none"
version: 1.2.1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.6.8
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.5
  dependency_validator: ^4.1.3
  dio: ^5.4.0
  esc_pos_utils_plus: ^2.0.3
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_database: ^11.3.6
  firebase_storage: ^12.4.6
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^15.1.2
  go_router_builder: ^2.4.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.10
  image_picker: ^1.0.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  logger: ^2.1.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  pluto_grid: ^8.0.0
  print_bluetooth_thermal: ^1.1.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2
  sign_button: ^2.0.6
  skeletonizer: ^2.0.1
  syncfusion_flutter_calendar: ^29.2.7
  syncfusion_localizations: ^29.2.7
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  device_info_plus: ^11.4.0
  flutter_gen: ^5.3.2
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.10
  riverpod_lint: ^2.3.9
dependency_overrides:
  intl: any
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
