name: aguazullavapp
description: Proyecto para lavadero de carros, control de pagos, etc.
publish_to: 'none'
version: 0.5.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.13.6
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.5
  dependency_validator: ^3.2.3
  dio: ^5.4.0
  file_selector: ^1.0.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.13
  firebase_database: ^10.3.8
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  go_router_builder: ^2.4.1
  google_sign_in: ^6.2.1
  google_sign_in_web_redirect: ^0.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.10
  image_picker: ^1.0.2
  install_plugin: ^2.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2
  sign_button: ^2.0.6
  skeletonizer: ^1.0.1
  upgrader: ^9.0.0
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  custom_lint: ^0.6.0
  device_info_plus: ^9.1.2
  flutter_gen: ^5.3.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.10
  riverpod_lint: ^2.3.9

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
